import type { Metadata } from "next";
import { Inter, Rubik, Vazirmatn, Syncopate } from "next/font/google";

import { cn } from "@/lib/utils";

import { getCurrentLocale } from "@/locales/server";

import Navbar from "@/components/layout/navbar";

import "../globals.css";

const rubik = Rubik({
  subsets: ["hebrew", "arabic", "latin"],
  variable: "--font-hebrew",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/logos/brand_black.svg",
        href: "/logos/brand_black.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/logos/brand_white.svg",
        href: "/logos/brand_white.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = getCurrentLocale();
  return (
    <html lang={locale} className={` ${rubik.variable}  scroll-smooth`}>
      <body className={" px-96 text-secondary bg-primary flex flex-col"}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
