import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getCurrentLocale } from "@/locales/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/logos/brand_black.svg",
        href: "/logos/brand_black.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/logos/brand_white.svg",
        href: "/logos/brand_white.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = getCurrentLocale();
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
