import type { Metadata } from "next";
import { Inter, Rubik, Vazirmatn } from "next/font/google";

import { cn } from "@/lib/utils";

import { getCurrentLocale } from "@/locales/server";

import Navbar from "@/components/layout/navbar";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });
const rubik = Rubik({
  subsets: ["hebrew"],
  variable: "--font-hebrew",
  weight: "300",
});

const vazirmatn = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-arabic",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/logos/brand_black.svg",
        href: "/logos/brand_black.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/logos/brand_white.svg",
        href: "/logos/brand_white.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = getCurrentLocale();
  return (
    <html
      lang={locale}
      className={`${inter.className} ${rubik.variable} ${vazirmatn.variable} $ scroll-smooth`}
    >
      <body
        className={cn(
          {
            "text-right font-hebrew  ": locale === "he",
            "text-right font-arabic ": locale === "ar",
          },
          " px-96 text-secondary"
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
